# Site Settings
lang: en
title: Cloud Network Journey
tagline: Cloud Network Journey
email: ryan@wetzellabs.com
description: >
   My Journey through Learning networking, cloud, and other technologies.

url: "https://www.cloudnetworkjourney.com"

# custom navigation
header_pages:
  - about.md
  - tutorial.md

# permalink: pretty

#collections:
#  authors:
#    output: true

#defaults:
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#      author: "Ryan Wetzelberger"
#  - scope:
#      path: ""
#    values:
#      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#remote_theme: chrisrhymes/bulma-clean-theme
theme: minima

#minima:

github_username:  ryanwetzelberger
linkedin_username: ryanwetzelberger

paginate: 5
paginate_path: "/blog/page:num"